services:
    desktop:
        image: giok94/linux-desktop:debian-13.4-guacamole
        build:
            context: .
        container_name: desktop
        environment:
            - TZ=Asia/Tbilisi
            - USERNAME=abc
            - USER_PASSWORD=abc
        volumes:
            - ./config:/config
            - ./app:/app
        shm_size: "1gb"
        restart: unless-stopped

    guacd:
        image: guacamole/guacd:1.6.0
        container_name: guacd
        restart: unless-stopped

    guacamole:
        image: guacamole/guacamole:1.6.0
        container_name: guacamole
        environment:
            - GUACD_HOSTNAME=guacd
            - GUACD_PORT=4822
            - POSTGRESQL_HOSTNAME=host.docker.internal
            - POSTGRESQL_PORT=5432
            - POSTGRESQL_DATABASE=guacamole_db
            - POSTGRESQL_USERNAME=guacamole_user
            - POSTGRESQL_PASSWORD=guacamole_password
        ports:
            - 9050:8080
        depends_on:
            - guacd
        restart: unless-stopped

