services:
    rdesktop:
        image: giok94/linux-rdp:debian-13.4
        build:
            context: .
        container_name: rdesktop
        environment:
            - TZ=Asia/Tbilisi
            - USERNAME=abc
            - USER_PASSWORD=abc
        volumes:
            - ./config:/config
            - ./app:/app
            - ./init.sh:/root/system_init.sh
        ports:
            # - 3390:3389
            # - 2222:22
            - 6080:6080
        shm_size: "1gb"
        restart: unless-stopped