services:
    rdesktop:
        image: giok94/linux-rdp:debian-12
        build:
            context: .
        container_name: rdesktop
        environment:
            - PUID=1000
            - PGID=1000
            - TZ=Asia/Tbilisi
        volumes:
            - ./config:/config
            - ./app:/app
        ports:
            - 3390:3389
            - 2222:22
        shm_size: "1gb"
        restart: unless-stopped
